### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by monicalavale-github** [Baeldung/spring-security-registration#111]
Hi,

I was able to successfully register using Gmail account. I could successfully complete the verification process which have set USER_ACCOUNT.ENABLED to 1 against my user account row in database.

But now when I try to login, I get following exception

j.l.RuntimeException: com.maxmind.geoip2.exception.AddressNotFoundException: The address 0:0:0:0:0:0:0:1 is not in the database.
	at o.b.s.MySimpleUrlAuthenticationSuccessHandler.loginNotification(MySimpleUrlAuthenticationSuccessHandler.java:63)
	at o.b.s.MySimpleUrlAuthenticationSuccessHandler.onAuthenticationSuccess(MySimpleUrlAuthenticationSuccessHandler.java:53)
	at o.s.s.w.a.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:326)
	at o.s.s.w.a.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:240)
	at o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	... 36 frames truncated
Caused by: c.m.g.e.AddressNotFoundException: The address 0:0:0:0:0:0:0:1 is not in the database.
	at c.m.g.DatabaseReader.get(DatabaseReader.java:188)
	at c.m.g.DatabaseReader.city(DatabaseReader.java:233)
	at o.b.s.DeviceService.getIpLocation(DeviceService.java:113)
	at o.b.s.DeviceService.verifyDevice(DeviceService.java:57)
	at o.b.s.MySimpleUrlAuthenticationSuccessHandler.loginNotification(MySimpleUrlAuthenticationSuccessHandler.java:59)
	... 40 common frames omitted

I tried both ways. First by entering only email and password, gives above exception. And then I entered email, password and verification token in the Google Authenticator Verification Code field.

How can I fix this login error?

**Comment by fanatixan** [comment]
Hello @monicalavale-github,

Do you face this issue with the code in this repo or your custom code?

If the former, could you please provide the steps to reproduce the problem?

Thanks.

**Comment by monicalavale-github** [comment]
I figured I was getting that exception because I was hosting the app at work location, and GeoIP2 could not find the location of my localhost address 0:0:0:0:0:0:0:1. I disabled the device recognition part of code, and I can now login to the app.

**Comment by eugenp** [comment]
Cool beans, closing here.

**Comment by raowaqasakram** [comment]
I am working with spring security, I'm getting this error while "sign-in ".

Caused by: c.m.g.e.AddressNotFoundException: The address 0:0:0:0:0:0:0:1 is not in the database.

I'm using this code

**Comment by jamshaid120** [comment]
> I am working with spring security, I'm getting this error while "sign-in ".
> 
> Caused by: c.m.g.e.AddressNotFoundException: The address 0:0:0:0:0:0:0:1 is not in the database.
> 
> I'm using this code

Why don't you try to disable the device recognition? This error code is the same as yours. So, it should work for you as well
