### ISSUE TITLE
   Exception encountered during context initialization -

### ISSUE THREAD

**Issue by thecoder8890** [Baeldung/spring-security-registration#119]
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.4.RELEASE)

web - 2020-02-18 21:23:52,835 [main] INFO  o.b.Application - Starting Application on AIPL-PUN-LT206 with PID 4124 (D:\LearningNewTech\Spring\registration\spring-security-registration\target\classes started by mingle in D:\LearningNewTech\Spring\registration\spring-security-registration)
web - 2020-02-18 21:23:52,839 [main] DEBUG o.b.Application - Running with Spring Boot v2.0.4.RELEASE, Spring v5.0.8.RELEASE
web - 2020-02-18 21:23:52,842 [main] INFO  o.b.Application - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/D:/Users/mingle/.m2/repository/org/codehaus/groovy/groovy/2.4.15/groovy-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
web - 2020-02-18 21:23:55,439 [main] INFO  o.a.c.h.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8081"]
web - 2020-02-18 21:23:55,449 [main] INFO  o.a.c.c.StandardService - Starting service [Tomcat]
web - 2020-02-18 21:23:55,450 [main] INFO  o.a.c.c.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.32
web - 2020-02-18 21:23:55,457 [localhost-startStop-1] INFO  o.a.c.c.AprLifecycleListener - The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Program Files\Java\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:/Program Files/Java/bin/server;C:/Program Files/Java/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\PuTTY\;C:\Program Files\Java\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\nodejs\;D:\Users\mingle\AppData\Local\Microsoft\WindowsApps;;D:\Users\mingle\Downloads\software\eclipse-jee-2019-12-R-win32-x86_64\eclipse;;.]
web - 2020-02-18 21:23:55,773 [localhost-startStop-1] INFO  o.a.c.c.C.[.[.[/] - Initializing Spring embedded WebApplicationContext
web - 2020-02-18 21:23:55,946 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean]: Factory method 'entityManagerFactory' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
web - 2020-02-18 21:23:55,949 [main] INFO  o.a.c.c.StandardService - Stopping service [Tomcat]
web - 2020-02-18 21:23:56,010 [main] ERROR o.s.b.SpringApplication - Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean]: Factory method 'entityManagerFactory' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
	at o.s.b.f.s.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	... 14 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean]: Factory method 'entityManagerFactory' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at o.s.b.f.s.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
	... 18 common frames omitted
Caused by: o.s.b.f.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
	at o.s.b.f.s.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	... 18 frames truncated
	... 19 common frames omitted
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at o.s.b.f.s.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
	... 41 common frames omitted
Caused by: j.l.IllegalStateException: Could not load JDBC driver class [org.h2.Driver]
	at o.s.j.d.DriverManagerDataSource.setDriverClassName(DriverManagerDataSource.java:130)
	at o.b.s.PersistenceJPAConfig.dataSource(PersistenceJPAConfig.java:51)
	at o.b.s.PersistenceJPAConfig$$EnhancerBySpringCGLIB$$b1ec8e82.CGLIB$dataSource$2(<generated>)
	at o.b.s.PersistenceJPAConfig$$EnhancerBySpringCGLIB$$b1ec8e82$$FastClassBySpringCGLIB$$86573e62.invoke(<generated>)
	at o.s.c.p.MethodProxy.invokeSuper(MethodProxy.java:228)
	... 7 frames truncated
	... 42 common frames omitted
Caused by: j.l.ClassNotFoundException: org.h2.Driver
	at j.i.l.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at j.i.l.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at j.l.ClassLoader.loadClass(ClassLoader.java:521)
	at j.l.Class.forName0(Class.java)
	at j.l.Class.forName(Class.java:416)
	... 1 frames truncated
	... 53 common frames omitted

**Comment by dkapil** [comment]
Hi @thecoder8890 
The current code base only supports Java 8, please reopen this issue if it's happening on Java 8 as well.
