### ISSUE TITLE
The address 0:0:0:0:0:0:0:1 is not in the database.

### ISSUE THREAD

**Issue by raowaqasakram** [Baeldung/spring-security-registration#121]
I was able to successfully register using Gmail account. I could successfully complete the verification process which have set USER_ACCOUNT.ENABLED to 1 against my user account row in database.

But now when I try to login, I get following exception

j.l.RuntimeException: com.maxmind.geoip2.exception.AddressNotFoundException: The address 0:0:0:0:0:0:0:1 is not in the database.
at o.b.s.MySimpleUrlAuthenticationSuccessHandler.loginNotification(MySimpleUrlAuthenticationSuccessHandler.java:63)
at o.b.s.MySimpleUrlAuthenticationSuccessHandler.onAuthenticationSuccess(MySimpleUrlAuthenticationSuccessHandler.java:53)
at o.s.s.w.a.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:326)
at o.s.s.w.a.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:240)
at o.s.s.w.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
... 36 frames truncated
Caused by: c.m.g.e.AddressNotFoundException: The address 0:0:0:0:0:0:0:1 is not in the database.
at c.m.g.DatabaseReader.get(DatabaseReader.java:188)
at c.m.g.DatabaseReader.city(DatabaseReader.java:233)
at o.b.s.DeviceService.getIpLocation(DeviceService.java:113)
at o.b.s.DeviceService.verifyDevice(DeviceService.java:57)
at o.b.s.MySimpleUrlAuthenticationSuccessHandler.loginNotification(MySimpleUrlAuthenticationSuccessHandler.java:59)
... 40 common frames omitted

**Comment by nikoma** [comment]
Same here

**Comment by shalltalk** [comment]
It can be fixed by setting the "geo.ip.lib.enabled" in application.properties to false.

**Comment by lor6** [comment]
We've now added a feature toggle for the geo ip library, which is disabled by default.
See section: https://github.com/Baeldung/spring-security-registration#feature-toggle-for-geo-ip-lib
