### ISSUE TITLE
error in registration process

### ISSUE THREAD

**Issue by AsterixKo** [Baeldung/spring-security-registration#150]
Hi,
I'm using ubuntu and eclipse.
I enter to the page http://localhost:8081/registration.html
I put my name, and email, and all the data.

And I have the next error in page when I push the button:

"Se produjo un error"

And the console output:

web - 2020-07-25 21:06:08,206 [http-nio-8081-exec-4] ERROR c.b.w.e.RestResponseEntityExceptionHandler - 500 Status Code
o.s.m.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at o.s.m.j.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
	at o.s.m.j.JavaMailSenderImpl.send(JavaMailSenderImpl.java:323)
	at o.s.m.j.JavaMailSenderImpl.send(JavaMailSenderImpl.java:312)
	at c.b.r.l.RegistrationListener.confirmRegistration(RegistrationListener.java:43)
	at c.b.r.l.RegistrationListener.onApplicationEvent(RegistrationListener.java:34)
	... 86 frames truncated
Caused by: j.m.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465
	at c.s.m.s.SMTPTransport.openServer(SMTPTransport.java:2211)
	at c.s.m.s.SMTPTransport.protocolConnect(SMTPTransport.java:722)
	at j.m.Service.connect(Service.java:342)
	at o.s.m.j.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
	at o.s.m.j.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
	... 90 common frames omitted
Caused by: j.n.s.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at s.s.s.Alert.createSSLException(Alert.java:131)
	at s.s.s.TransportContext.fatal(TransportContext.java:326)
	at s.s.s.TransportContext.fatal(TransportContext.java:269)
	at s.s.s.TransportContext.fatal(TransportContext.java:264)
	at s.s.s.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
	... 15 frames truncated
	... 94 common frames omitted
Caused by: s.s.v.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at s.s.v.PKIXValidator.doBuild(PKIXValidator.java:439)
	at s.s.v.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at s.s.v.Validator.validate(Validator.java:264)
	at s.s.s.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at s.s.s.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	... 2 frames truncated
	... 109 common frames omitted
Caused by: s.s.p.c.SunCertPathBuilderException: unable to find valid certification path to requested target
	at s.s.p.c.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at s.s.p.c.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at j.s.c.CertPathBuilder.build(CertPathBuilder.java:297)
	at s.s.v.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 115 common frames omitted

**Comment by lor6** [comment]
Hi @AsterixKo This usually happens when the property spring.mail.properties.mail.smtps.starttls.enable=true is missing. Please check that you've kept this in the properties file.
Also note that Google has higher security restrictions by default. You may need to enable access for less secure apps before being able to login from the app: https://support.google.com/accounts/answer/6010255?hl=en Make sure to turn this back off once you're done testing.
