### ISSUE TITLE
Runtime error due to rest-assured dependency

### ISSUE THREAD

**Issue by Elshid** [Baeldung/spring-security-registration#167]
When starting the project, spring-boot returns the following exception:

    java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
    	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
    	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit> GoovyClassValueFactory.java:35)
    	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
     	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
    	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
    	at    org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
    	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>  (MetaClassRegistryImpl.java:108)
    	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init> (MetaClassRegistryImpl.java:86)
    	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
     	at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.<init> (GroovyBeanDefinitionReader.java:150)
     	at org.springframework.boot.BeanDefinitionLoader.<init>(BeanDefinitionLoader.java:85)
     	at org.springframework.boot.SpringApplication.createBeanDefinitionLoader(SpringApplication.java:738)
    	at org.springframework.boot.SpringApplication.load(SpringApplication.java:681)
    	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
     	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
     	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
    	at com.baeldung.Application.main(Application.java:13)
    web - 2021-04-24 18:40:33,725 [main] ERROR o.s.b.SpringApplication - Application run failed
    j.l.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
    	at o.c.g.r.d.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
    	at j.i.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
    	at j.i.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
     	at j.i.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     	at j.l.r.Constructor.newInstanceWithCaller(Constructor.java:500)
    	... 14 frames truncated

This bug exists due to the dependency "rest-assured", which has groovy as a dependency.

**Comment by F-Baker** [comment]
I found thymeleaf-layout-dialect is also affected.  Removing both dependencies and the implementing classes resolved the failure to compile.
