### ISSUE TITLE
Unable to resolve JDBC type code for column `roles.users`

### ISSUE THREAD

**Issue by zafarale** [Baeldung/spring-security-registration#187]
Caused by: org.hibernate.HibernateException: Unable to resolve JDBC type code for column `roles.users`
	at org.hibernate.mapping.Column.getSqlType(Column.java:297)
	at org.hibernate.tool.schema.internal.StandardTableExporter.getSqlCreateStrings(StandardTableExporter.java:99)
	... 108 more
Caused by: org.hibernate.HibernateException: No type mapping for org.hibernate.type.SqlTypes code: 2003 (ARRAY)
	at org.hibernate.type.descriptor.sql.spi.DdlTypeRegistry.getTypeName(DdlTypeRegistry.java:158)
	at org.hibernate.type.descriptor.sql.spi.DdlTypeRegistry.getTypeName(DdlTypeRegistry.java:138)
	at org.hibernate.mapping.Column.getSqlTypeName(Column.java:269)
	at org.hibernate.mapping.Column.getSqlType(Column.java:293)
	... 109 more

`@Entity
@Table(name = "USERS")
@Data
@SuperBuilder()
@NoArgsConstructor @AllArgsConstructor @RequiredArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class User extends AbstractModel<UUID> {
  
  private static final long serialVersionUID = 2222189507012413537L;
  
  @NonNull
  @Column(unique=true)
  private String userName;
  
  @NonNull
  @Column(unique=true, updatable = false, nullable = false)
  private String email;
  
  private String firstName;
  
  private String lastName;
  
  private Boolean activated;
  
  @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
  @JoinTable(name = "USER_ROLES", 
        joinColumns = 
        @JoinColumn(name = "uuid", insertable = true, updatable = false), 
        inverseJoinColumns = 
        @JoinColumn(name = "ruid", insertable = true, updatable = false))
  private Collection<Role> roles;

  @Override @Id @GeneratedValue(generator = "UUID")
  public UUID getUid() {
    // TODO Auto-generated method stub
    return this.uid;
  }

  @Version
  public int getVersion() {
    // TODO Auto-generated method stub
    return this.version;
  }

  @Override
  public void setUid(UUID uid) {
   this.uid = uid;
  }

@Entity @Table(name = "ROLES") @Data @SuperBuilder() @NoArgsConstructor @RequiredArgsConstructor @EqualsAndHashCode(callSuper = true) @ToString(callSuper = true)
public class Role extends AbstractModel<UUID> {

  private static final long serialVersionUID = 4302128543375021842L;
  /**
   * Role name
   */
  @NonNull
  private String name;

  /**
   * 
   */
  @ManyToMany(mappedBy = "roles")
  private Set<User> users;

  @Override @Id @GeneratedValue(generator = "UUID")
  public UUID getUid() {
    // TODO Auto-generated method stub
    return this.uid;
  }

  @Version
  public int getVersion() {
    // TODO Auto-generated method stub
    return this.version;
  }

  @Override
  public void setUid(UUID uid) {
    this.uid = uid;
  }

  public void setVersion(int version) {
    this.version = version;
  }

}

  
  public void setVersion(int version) {
    this.version = version;
  }
  
}

@MappedSuperclass
@SuperBuilder @NoArgsConstructor @AllArgsConstructor @EqualsAndHashCode
public abstract class AbstractModel<K extends Serializable> implements Model<K> {

  private static final long serialVersionUID = -8840425136994685035L;

  
  protected K uid;

  //@JsonIgnore
  protected int version;

}
`

Unable to make it work, please suggest a solution

**Comment by ulisseslima** [comment]
Hey @zafarale.

Can you link to the article you're having issues with?
