### ISSUE TITLE
Application does not run when deployed to web container (Liberty as an example)

### ISSUE THREAD

**Issue by marioja** [Baeldung/spring-security-registration#213]
I get this error in the console
```
Caused by: j.i.FileNotFoundException: src\main\resources\maxmind\GeoLite2-Country.mmdb (The system cannot find the path specified)
	at j.i.RandomAccessFile.open0(RandomAccessFile.java)
	at j.i.RandomAccessFile.open(RandomAccessFile.java:316)
	at j.i.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at c.m.d.BufferHolder.<init>(BufferHolder.java:20)
	at c.m.d.Reader.<init>(Reader.java:117)
	... 14 frames truncated
	... 63 common frames omitted
[ERROR   ] SRVE0285E: Exception caught while destroying context: java.lang.NullPointerException
	at org.jboss.weld.module.web.servlet.WeldInitialListener.contextDestroyed(WeldInitialListener.java:113)
	at [internal classes]
```

See PR #212 for a fix

**Comment by ulisseslima** [comment]
Fix merged.
