### ISSUE TITLE
535 AUTH failed

### ISSUE THREAD

**Issue by CoolR7** [Baeldung/spring-security-registration#39]
Hi
I have been using the below data on email properties files 
smtp.host=smtp-relay.gmail.com
smtp.port=587
smtp.protocol=smtps
smtp.username=myemail@gmail.com
smtp.password=mypassword
support.email=myemail@gmail.com

and getting the below exception

caused by: j.m.AuthenticationFailedException: 535 AUTH failed
at c.s.m.s.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
	at c.s.m.s.SMTPTransport.authenticate(SMTPTransport.java:843)
	at c.s.m.s.SMTPTransport.protocolConnect(SMTPTransport.java:748)
	at j.m.Service.connect(Service.java:366)

I have tried all the other option of host for gmail with different port number and none of the options has worked.
Could you please provide a working properties value for gmail .smtp

**Comment by eugenp** [comment]
Well, @CoolR7 - that's not going to be possible. SMTP credentials are naturally user-specific, so I can't commit my own Gmail credentials here :)
What I would say is - Gmail is just one option - there are many available email solutions out there, all providing simple SMTP credentials. So - you might want to have a look at Amazon SES for example, or SendGrid. 

Hope that helps. 
Cheers, 
Eugen.

**Comment by mrcleanandfresh** [comment]
I get this same error using the FakeSMTP server on a fresh clone: 02-24-2018. Everything else works awesomely, I just can't go through the flow of using the verification token. Here's the stack trace I am getting after the `RegistrationListener#confirmRegistration()` method fires:
`o.s.m.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535 AUTH failed

	at o.s.m.j.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:424)
	at o.s.m.j.JavaMailSenderImpl.send(JavaMailSenderImpl.java:307)
	at o.s.m.j.JavaMailSenderImpl.send(JavaMailSenderImpl.java:296)
	at o.b.r.l.RegistrationListener.confirmRegistration(RegistrationListener.java:43)
	at o.b.r.l.RegistrationListener.onApplicationEvent(RegistrationListener.java:34)
	... 89 frames truncated
Caused by: j.m.AuthenticationFailedException: 535 AUTH failed

	at c.s.m.s.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
	at c.s.m.s.SMTPTransport.authenticate(SMTPTransport.java:843)
	at c.s.m.s.SMTPTransport.protocolConnect(SMTPTransport.java:748)
	at j.m.Service.connect(Service.java:366)
	at o.s.m.j.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:501)
	... 1 frames truncated
	... 93 common frames omitted`

email.properties:
`smtp.host=localhost
smtp.port=2525
smtp.protocol=smtp
smtp.username=test
smtp.password=test`

I'm running the FakeSMTP server on port 2525. I also couldn't get it to work with SES, or my domain's SMTP email. I'm almost certain it's something I am doing wrong, since I went through this tutorial to learn about how to register users and manage them. Any help would be appreciated.

**Comment by mrcleanandfresh** [comment]
Thanks @lor6, my apologies, I thought since it was the same issue it would have been redundant. I changed the properties in application.properties and it worked! Thanks. I had thought it was weird that in troubleshooting using Google that spring mail was listed like spring.mail.host, etc and the email.properties file wasn't.

Anyway, there are two files called `email.properties.sample` and `email.properties.sample.localhost` and in them it says to rename them from `.sample` to `email.properties`. Here's the comment in the localhost one:

################### JavaMail Configuration ##########################
# To setup a local smtp server for testing, do the following:
#
# Rename this file to email.properties
# Download FakeSMTP
# git clone https://github.com/Nilhcem/FakeSMTP
# cd FakeSMTP
# mvn compile package
# Start the fakeSMTP server on port 2525
# java -jar target/fakeSMTP-*.jar
